#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/PostProcessCommon.ush"
#include "/Engine/Private/ScreenPass.ush"

SCREEN_PASS_TEXTURE_VIEWPORT(Input)

Texture2D InTexture;
SamplerState Sampler;

#if PIXELSHADER

void MainPS(float4 SvPosition : SV_POSITION, out float4 OutColor : SV_Target0)
{
	float2 UV = SvPosition.xy * Input_ExtentInverse;
	//OutColor = Texture2DSample(InTexture, Sampler, UV);
	OutColor = float4(1,1,1,1);
}    

#endif